Add featured posts to home page
codefordc/opendatadc pull request #58
Opened 2017-04-14 17:57 UTC by gregjd

This is the thing I worked on at the most recent session (at Learning Objects).

It has a bunch of old commits — most/all of which were previously merged with codefordc's version — but they're showing up here because of branching issues (I was having trouble pulling codefordc's commits into my branch). Rather than delaying while I fix the branch issues, I figured I'd just get this in here. But yeah, it's the most recent commit that's where the magic is.

2017-05-02 00:05 UTC, mkalish requested changes
I can show you how to rebase (remove the old commits) your changes back onto the master branch

2017-05-02 00:05 UTC, mkalish commented on ckanext/open_data_dc/templates/home/snippets/test.html
> +<section class="module-content categories-list">
I think file name should change to more descriptive.

2017-05-02 00:05 UTC, mkalish commented on ckanext/open_data_dc/templates/snippets/least_popular_groups.html
> +{# Renders a list of the site's least popular groups. #}
I don't think this is used?

2017-06-06 00:20 UTC, closed without merging

2017-06-06 00:29 UTC, gregjd commented
Replaced by https://github.com/codefordc/opendatadc/pull/61